name: Edit artifacts.json in helm-charts

on:
  workflow_call:
    inputs:
      scope:
        description: "Scope of artifacts.json file to update"
        type: string
        required: true
      type:
        description: "Artifact`s type"
        type: string
        required: false
        default: "docker"
      artifact-name:
        description: "Artifact`s name"
        type: string
        required: true
      artifact-tag:
        description: "Artifact`s tag"
        type: string
        required: true

jobs:
  update-artifacts-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout helm-charts repository
        uses: actions/checkout@v4
        with:
          repository: MapColonies/helm-charts
          path: helm-charts
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Modify artifacts.json
        run: |
          # Split string by comma
          echo "${{ inputs.scope }}" | tr ',' '\n' | while read -r element; do
            # cd to directory
            pushd helm-charts/$element
            node -e "
            const fs = require('fs');
            const path = './artifacts.json';
            let data = {};
            // Check if 'artifacts.json' file already exists
            if (fs.existsSync(path)) {
              data = JSON.parse(fs.readFileSync(path, 'utf8'));
            }
            // Ensure nested structure: docker -> registry -> scope -> artifact:tag
            if (!data['${{ inputs.type }}']['${{ secrets.ACR_URL }}']) data['${{ inputs.type }}']['${{ secrets.ACR_URL }}'] = {};
            const compositeKey = '${element}/${{ inputs.artifact-name }}';
            // Assign the artifact tag to the composite key
            data['${{ inputs.type }}']['${{ secrets.ACR_URL }}'][compositeKey] = '${{ inputs.artifact-tag }}';
            // Writing new file contents
            fs.writeFileSync(path, JSON.stringify(data, null, 2));
            "
            # go back to before pushd
            popd
          done

      - name: Commit changes
        run: |
          cd helm-charts
          git config --global user.name "mapcolonies[bot]"
          git config --global user.email "devops[bot]@mapcolonies.com"

          git add .
          # Add "|| true" for not failing on this line
          git commit -m "chore: update artifacts.json for ${{ inputs.scope }}" -m "with ${{ inputs.type }} artifact: ${{ inputs.artifact-name }}:${{ inputs.artifact-tag }}" || true

          success=false
          for ((i=1; i<=5; i++)); do
            echo "Attempt number $i"
            if git push; then
              success=true
              break
            else
              sleep 5
              # --ff for fast-forward
              git pull origin master --ff
            fi
          done

          if [ "$success" = false ]; then
            echo "Failed to push changes."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
